name: Bug Report
description: Create issue for reporting a bug.
title: [Bug]: 
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: "## Thanks for taking time to fill out this bug report!"
- type: textarea
  id: what-happend
  attributes:
    lable: Wath happend?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
  validations:
    required: true
