name: "Feature Request"
title: "[Feature]: "
labels: ["feature"]
body:
- type: textarea
  id: what-your-idea
  attributes:
    label: Tell us your idea
    description: "Tell us your idea"
  validations:
    required: true

